---
apiVersion: v1
kind: Service
metadata:
  name: springadmin-web-ui
spec:
  selector:
    run: springadmin
  type: NodePort
  ports:
  - name: web
    port: 80
    targetPort: 18888
    nodePort: 43181
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springadmin
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: springadmin
    spec:
      containers:
      - name: springadmin
        image: k8s.ipebg.com/apps/springadmin:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 18888
