---
- name: 創建{{BIN_DIR}} 目錄
  file:
    dest={{BIN_DIR}} 
    state=directory mode=0740

- name: 修改iptables FORWARD chain的默認策略設置
  iptables:
    chain=FORWARD
    policy=ACCEPT

- name: 保存iptables 規則配置
  command: iptables-save

- name: 複製Docker二進制執行文件
  copy:
    src={{DOCKER_DIR}}/{{item}} 
    dest={{BIN_DIR}}/{{item}} 
    mode=0540
  with_items:
  - docker
  - dockerd
  - docker-init
  - docker-proxy
  - docker-runc
  - docker-containerd
  - docker-containerd-ctr
  - docker-containerd-shim
 
- name: 創建/etc/docker目錄
  file:
    dest=/etc/docker
    state=directory

- name: 創建docker-daemon.json.j2 文件
  template:
    src=docker-daemon.json.j2
    dest=/etc/docker/daemon.json

- name: 創建docker.service 文件
  template:
    src=docker.service.j2
    dest=/etc/systemd/system/docker.service

- name: systemctl reload
  command: systemctl daemon-reload

- name: Sstarting Docker
  service: 
    name=docker
    state=restarted
    enabled=yes
